# Import the autogenerated selenium test data. Feel free to change the name is you want.
from test_demo import *
import time


def method():
    pass


def main():

    # Global variables
    yes_cita = False
    attempts = 1

    while True:

        print(f"Try NO.{attempts}. Go go go!")

        # Call the test function to automatically fill up the forms
        test = TestDemo()
        test.setup_method(method)
        test.test_demo()

        # Try again in x minutes
        time.sleep(60)

        attempts += 1


if __name__ == "__main__":
    main()
